### ISSUE TITLE
SharePoint 2013 Error

### ISSUE THREAD

**Issue by jeffangama** [wictorwilen/gulp-spsync#20]
Hello,

I've configured it for a new project as usual, but this time when i save a file (gulp watch), it throws this error. Any idea where i shall look into this issue ?

Thank you,

```
[09:59:55] Locating STS Url for
[09:59:56] STS Endpoint found https://accounts.accesscontrol.windows.net/tokens/OAuth/2
Unhandled rejection StatusCodeError: 401 - "{\"error\":\"invalid_client\",\"error_description\":\"AADSTS70002: Unable to determine the tenant identifier from the request. Client ID '5aa2595c-9be5-42b5-af80-c821665a2d29@' is not valid. AADSTS90022: Prinapp1al name format is invalid for '5aa2595c-9be5-42b5-af80-c821665a2d29@'.
Expected name[/instance][@realm].\\r\\nTrace ID: 32382b18-53e8-451d-8d04-39c33c2f5100\\r\\nCorrelation ID: 0a0e1022-1f35-4d51-a7f7-30c4f901fcbc\\r\\nTimestamp: 2018-08-21 07:59:56Z\",\"error_codes\":[70002,90022],\"timestamp\":\"2018-08-21 07:59:56Z\",\"trace_id\":\"32382b18-53e8-451d-8d04-39c33c2f5100\",\"correlation_id\":\"0a0e1022-1f35-4d51-a7f7-30c4f901fcbc\"}"
    at new StatusCodeError (C:\dev\customer.app1\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\dev\customer.app1\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\dev\customer.app1\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\dev\customer.app1\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\dev\customer.app1\node_modules\request\request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\dev\customer.app1\node_modules\request\request.js:1001:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

My gulpfile.js

```
var gulp = require('gulp')
var sp = require('gulp-spsync')
var watch = require('gulp-watch')
var settings = {
    "client_id": "5aa2595c-9be5-42b5-af80-c821665a2d29",
    "client_secret": "SUzDLo/77e242VOcqs4vt525rrylQMLgb/FHt1e9qAk=",
    "realm": "",
    "site": "https://xxxxx/sites/xxx",
    "verbose": "true",
    "watch": "true"
};

var settingsSearch = {
    "client_id": "6207fa90-2b0e-4067-b8fe-1aae6cb3926f",
    "client_secret": "ZCmjRLuiAU+HszBYnnOuwvErI+L2fTyO4aKgyccGNQ8=",
    "realm": "",
    "site": "https://xxx/sites/xx/xxx2",
    "verbose": "true",
    "watch": "true"
};

gulp.task('deploySite', function () {
    return gulp.src('src/**/*.*')
        .pipe(watch('src/**/*.*'))
        .pipe(sp(settings))
        .pipe(gulp.dest('build'))
})

gulp.task('deployToSearch', function () {
    return gulp.src('src/**/*.*')
        .pipe(watch('src/**/*.*'))
        .pipe(sp(settingsSearch))
        .pipe(gulp.dest('build'))
})
```

I ran : deploySite gulp task

Thank you

**Comment by jeffangama** [comment]
Oh its because on premise isnt supported unfortunately !
