### ISSUE TITLE
Application with identifier was not found in the directory 

### ISSUE THREAD

**Issue by xsolon** [wictorwilen/gulp-spsync#9]
The app is listed in App permissions, tried a few times. Trying to upload to Site Assets.
Any idea about what could be wrong?

Replaced some ids

C:\Users\user\Source\Repos\test1\charts\Test1\test1Sp>gulp
[16:49:10] Using gulpfile ~\Source\Repos\test1\charts\Test1\test1Sp\gulpfile.js
[16:49:10] Starting 'default'...
running default
[16:49:10] Verbose logging on!
[16:49:10] Uploading SiteAssets\folder\README.txt
[16:49:10] Locating realm for https://o365test1.sharepoint.com
[16:49:10] Realm is 40d2cf2d-1b83-48ba-998c-000000000000
[16:49:10] Retreiving access token for  d6c54594-f5e6-4958-8385-000000000000@40d2cf2d-1b83-48ba-998c-000000000000
[16:49:10] Locating STS Url for
[16:49:11] STS Endpoint found https://accounts.accesscontrol.windows.net/tokens/OAuth/2
{"headers":{"Content-Type":"application/x-www-form-urlencoded"},"form":{"grant_type":"client_credentials","client_id":"d6c54594-f5e6-4958-8385-000000000000@40d2cf2d-1b83-48ba-998c-000000000000","client_secret":"secret=","resource":"00000003-0000-0ff1-ce00-000000000000/o365test1.sharepoint.com@40d2cf2d-1b83-48ba-998c-000000000000"}}
Unhandled rejection StatusCodeError: 400 - {"error":"unauthorized_client","error_description":"AADSTS70001: Application with identifier 'd6c54594-f5e6-4958-8385-000000000000' was not found in the directory 40d2cf2d-1b83-48ba-998c-000000000000\r\nTrace ID: 36f197b6-2e00-47d8-a957-00\r\nCorrelation ID: 60f4380f-92ed-490e-907c-00\r\nTimestamp: 2016-09-04 20:49:11Z","error_codes":[70001],"timestamp":"2016-09-04 20:49:11Z","trace_id":"36f197b6-2e00-47d8-00","correlation_id":"60f4380f-92ed-490e-907c-00"}
    at new StatusCodeError (C:\Users\user\Source\Repos\test1\charts\Test1\test1Sp\node_modules\request-promise\lib\errors.js:26:15)
    at Request.RP$callback [as _callback](C:UsersuserSourceRepostest1chartsTest1test1Spnode_modulesrequest-promiselibrp.js:68:32)
    at Request.self.callback (C:\Users\user\Source\Repos\test1\charts\Test1\test1Sp\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\user\Source\Repos\test1\charts\Test1\test1Sp\node_modules\request\request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\user\Source\Repos\test1\charts\Test1\test1Sp\node_modules\request\request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by kmaneshk** [comment]
hi @xsolon seems like the application has not got registered correctly. Have you followed the step to set up the app for using client credentials, from the appinv.aspx page?

Instructions for setting up gulp-spsync are on this page here https://github.com/wictorwilen/gulp-spsync

**Comment by wictorwilen** [comment]
@xsolon - did you really follow the instructions?

**Comment by wictorwilen** [comment]
@xsolon - did you really follow the instructions?

**Comment by xsolon** [comment]
I thought I did (see attached). I'll try again. I did use a partner account.  I wonder if that makes a difference.
In any case you are saying this is an app registration issue.

**Comment by xsolon** [comment]
I thought I did (see attached). I'll try again. I did use a partner account.  I wonder if that makes a difference.
In any case you are saying this is an app registration issue.

**Comment by xsolon** [comment]
I thought I did (see attached). I'll try again. I did use a partner account.  I wonder if that makes a difference.
In any case you are saying this is an app registration issue.

**Comment by xsolon** [comment]
I thought I did (see attached). I'll try again. I did use a partner account. I wonder if that makes a difference.
In any case you are saying this is an app registration issue.
https://noworky.png

**Comment by wictorwilen** [comment]
I think the Guid looks a bit suspicious with that many trailing zeroes...

**Comment by xsolon** [comment]
I replaced them manually before taking the picture as this is a prod environment.

**Comment by xsolon** [comment]
Using a non-partner account resolved the issue.
